### ISSUE TITLE
FlowError: Cannot import the value fromPlainObject

### ISSUE THREAD

**Issue by tbergq** [kiwicom/orbit-components#1010]
After upgrading to latest version of flow, I get these two flow errors: 

```
Cannot import the value fromPlainObject as a type. import type only works on type exports like type aliases, interfaces,
and classes. If you intended to import the type of a value use import typeof instead
```
and 
```
Cannot import the value getTokens as a type. import type only works on type exports like type aliases, interfaces, and
classes. If you intended to import the type of a value use import typeof instead
```

**Comment by mrtnzlml** [comment]
@vepor Any updates on this issue, please? It starts affecting more and more teams.

**Comment by vepor** [comment]
@mrtnzlml We wanted to focus on this problem in the last two weeks, but we couldn't because we needed to deliver some functionalities for the main frontend app where we didn't want to update the flow now and postpone merging orbit to production. We gonna focus on this problem next week and we gonna upgrade flow to the latest version 🙂
