### ISSUE TITLE
Achive same design of kiwi's flight details using Orbit 

### ISSUE THREAD

**Issue by kouloughli-hemza** [kiwicom/orbit-components#1842]
Hello how can we achieve same tripSegment design , the one on this lib is not same as kiwi
is there a way we can achieve kiwi's one using Orbit ?

Thank you again

**Comment by vepor** [comment]
Hi @kouloughli-hemza,

we have planned introduction of new `Itinerary` components and probably also other sub-components that we will be needed for the same design. Sadly, because of current workload and other priorities we don't have any exact ETD and most likely we won't have time to focus on it until July.

**Comment by kouloughli-hemza** [comment]
Thank you for you reply @vepor 
i dnt know what to use for the moment to show flight search result ,
i see that TripSegment is now 'Deprecated in favor of the forthcoming ItinerarySegment.'
Another question is : 
can we combine between Orbit and Nitro ?
thank you

**Comment by vepor** [comment]
Feel free to use the `TripSegment` and `TripSector` for now.

Yes you can. But nitro is suitable more for Kiwi.com projects than 3rd party applications, as it's very opinionated and solve a lot of stuff that you might not need in the end.
