### ISSUE TITLE
<ListItem /> optional margin

### ISSUE THREAD

**Issue by kubp** [kiwicom/orbit-components#356]
**Is your feature request related to a problem? Please describe.**
We need to add a different margin between items in `<List />`

**Describe the solution you'd like**
Have some prop that allows modifying `margin-bottom`.

**Additional context**
Goal:
![image](https://user-images.githubusercontent.com/7695341/45617157-bb39d380-ba71-11e8-9757-c7819f80a7ab.png)

**Comment by flanzana** [comment]
Hi! It's been almost 3 months since this was open and closed, but now I came accross with similar issue.

**Is your feature request related to a problem? Please describe.**
ListItem has default spacing margin-bottom: 4px which unfortunately cannot be modified. I need to make more spacing (12px or 16px). Example where 4px is just too tight: https://monosnap.com/file/wOpnWyk0Tk7lblIU451cs9WFoTvllP

**Describe the solution you'd like**
Please, add props spacing in `<List/>` (the same affect as spacing has in `<Stack/>`) or at least add spaceAfter in `<ListItem/>`.
